version: '3.8'

services:

  app:
    container_name: app_descomplica
    build:
        context: .
        dockerfile: Dockerfile.dev
    entrypoint: .docker/entrypoint.sh
    volumes:
      - .:/app/
    ports:
      - "{$PORT}:{$PORT}"
